# Guided Project: Mobile App for Lottery Addiction

## Introduction

Many people start playing the lottery for fun, but for some this activity turns into a habit which eventually escalates into addiction. Like other compulsive gamblers, lottery addicts soon begin spending from their savings and loans, they start to accumulate debts, and eventually engage in desperate behaviors like theft.

A medical institute that aims to prevent and treat gambling addictions wants to build a dedicated mobile app to help lottery addicts better estimate their chances of winning. The institute has a team of engineers that will build the app, but they need us to create the logical core of the app and calculate probabilities.

For the first version of the app, they want us to focus on the 6/49 lottery and build functions that enable users to answer questions like:

- What is the probability of winning the big prize with a single ticket?
- What is the probability of winning the big prize if we play 40 different tickets (or any other number)?
- What is the probability of having at least five (or four, or three, or two) winning numbers on a single ticket?


## Core Functions

In [1]:
# create factorial function

def factorial(n):
    final_product = 1
    for i in range(n,0,-1):
        final_product *= i   
    return final_product

In [2]:
# create combinations function
def combinations(n,k):
    numerator = factorial(n)
    denominator = factorial(k) * factorial(n-k)
    return numerator / denominator

## One-ticket Probability

In the 6/49 lottery, six numbers are drawn from a set of 49 numbers that range from 1 to 49. A player wins the big prize if the six numbers on their tickets match all the six numbers drawn. If a player has a ticket with the numbers {13, 22, 24, 27, 42, 44}, he only wins the big prize if the numbers drawn are {13, 22, 24, 27, 42, 44}. If only one number differs, he doesn't win.

For the first version of the app, we want players to be able to calculate the probability of winning the big prize with the various numbers they play on a single ticket (for each ticket a player chooses six numbers out of 49). So, we'll start by building a function that calculates the probability of winning the big prize for any given ticket.

In [3]:
# create one-ticket probability function
def one_ticket_probability(numbers):
    total_outcomes = combinations(49,6)
    p_one_ticket = 1 / total_outcomes
    percentage = p_one_ticket * 100
    
    print('''Your chances to win the big prize with the numbers {} are {:.7f}%.
In other words, you have a 1 in {:,} chances to win.'''.format(numbers,
                    percentage, int(total_outcomes)))

In [4]:
# test 1
one_ticket_probability([1,2,3,4,5,6])

Your chances to win the big prize with the numbers [1, 2, 3, 4, 5, 6] are 0.0000072%.
In other words, you have a 1 in 13,983,816 chances to win.


In [5]:
# test 2
test_two = [49,37,25,13,1,5]
one_ticket_probability(test_two)

Your chances to win the big prize with the numbers [49, 37, 25, 13, 1, 5] are 0.0000072%.
In other words, you have a 1 in 13,983,816 chances to win.


## Historical Data Check for Canada Lottery

In [6]:
# read-in historical Data
import pandas as pd

history = pd.read_csv('649.csv')

In [7]:
history.shape

(3665, 11)

There are 11 columns and 3,665 lottery drawing records

In [8]:
history.head(3)

PRODUCT  DRAW NUMBER  SEQUENCE NUMBER  DRAW DATE  NUMBER DRAWN 1  \
0      649            1                0  6/12/1982               3   
1      649            2                0  6/19/1982               8   
2      649            3                0  6/26/1982               1   

   NUMBER DRAWN 2  NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  \
0              11              12              14              41   
1              33              36              37              39   
2               6              23              24              27   

   NUMBER DRAWN 6  BONUS NUMBER  
0              43            13  
1              41             9  
2              39            34

In [9]:
history.tail(3)

PRODUCT  DRAW NUMBER  SEQUENCE NUMBER  DRAW DATE  NUMBER DRAWN 1  \
3662      649         3589                0  6/13/2018               6   
3663      649         3590                0  6/16/2018               2   
3664      649         3591                0  6/20/2018              14   

      NUMBER DRAWN 2  NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  \
3662              22              24              31              32   
3663              15              21              31              38   
3664              24              31              35              37   

      NUMBER DRAWN 6  BONUS NUMBER  
3662              34            16  
3663              49             8  
3664              48            17

## Function for Historical Data Check

The engineering team told us that we need to be aware of the following details:

- Inside the app, the user inputs six different numbers from 1 to 49.
- Under the hood, the six numbers will come as a Python list and serve as an input to our function.
- The engineering team wants us to write a function that prints:
 - the number of times the combination selected occurred in the Canada data set; and
 - the probability of winning the big prize in the next drawing with that combination.


In [10]:
def extract_numbers(row):
    row = row[4:10]
    row = set(row.values)
    return row

In [11]:
# extract winning numbers from historical data
winning_numbers = history.apply(extract_numbers, axis=1)
winning_numbers.head()

0    {3, 41, 11, 12, 43, 14}
1    {33, 36, 37, 39, 8, 41}
2     {1, 6, 39, 23, 24, 27}
3     {3, 9, 10, 43, 13, 20}
4    {34, 5, 14, 47, 21, 31}
dtype: object

In [12]:
def check_historical_occurrence(user_numbers, historical_numbers):
    '''
    user_numbers: a Python Set
    historical_numbers: a Pandas series
    '''
    user_numbers_set = set(user_numbers)
    check_occurrence = historical_numbers == user_numbers_set
    n_occurrences = check_occurrence.sum()
    
    if n_occurrences == 0:
        print('''The combination {} has never occurred.
        This doesn\'t mean that these numbers are more likely to occur.
        Your chances to win the big prize in the next drawing using {} are 0.0000072%.
        In other words you have a 1 in 13,983,816 chance of winning.'''
              .format(user_numbers, user_numbers))
    else:
        print('''The combination {} has occurred {} times.
        This doesn\'t mean that these numbers are more likely to occur.
        Your chances to win the big prize in the next drawing using {} are 0.0000072%.
        In other words you have a 1 in 13,983,816 chance of winning.'''
              .format(user_numbers,n_occurrences, user_numbers))

In [13]:
# test function with random set of numbers
test_input_3 = [14,36,1,5,3,9]
check_historical_occurrence(test_input_3, winning_numbers)

The combination [14, 36, 1, 5, 3, 9] has never occurred.
        This doesn't mean that these numbers are more likely to occur.
        Your chances to win the big prize in the next drawing using [14, 36, 1, 5, 3, 9] are 0.0000072%.
        In other words you have a 1 in 13,983,816 chance of winning.


In [14]:
# test function with previous winning set
test_input_4 = [3, 41, 11, 12, 43, 14]
check_historical_occurrence(test_input_4, winning_numbers)

The combination [3, 41, 11, 12, 43, 14] has occurred 1 times.
        This doesn't mean that these numbers are more likely to occur.
        Your chances to win the big prize in the next drawing using [3, 41, 11, 12, 43, 14] are 0.0000072%.
        In other words you have a 1 in 13,983,816 chance of winning.


## Multi-ticket Probability

Lottery addicts usually play more than one ticket on a single drawing, thinking that this might increase their chances of winning significantly. Our purpose is to help them better estimate their chances of winning — on this screen, we're going to write a function that will allow the users to calculate the chances of winning for any number of different tickets.

We've talked with the engineering team and they gave us the following information:

- The user will input the number of different tickets they want to play (without inputting the specific combinations they intend to play).
- Our function will see an integer between 1 and 13,983,816 (the maximum number of different tickets).
- The function should print information about the probability of winning the big prize depending on the number of different tickets played.


In [33]:
def multi_ticket_probability(n_tickets):
    total_outcomes = combinations(49,6)
    p_mult_tickets = n_tickets / total_outcomes
    percentage = p_mult_tickets * 100
    
    if n_tickets == 1:
        print('''Your chances to win the big prize with one ticket are {:.7f}%.
In other words, you have a 1 in {:,} chance to win.'''.format(percentage, int(total_outcomes)))
    
    else:
        combinations_simplified = round(total_outcomes/n_tickets)
        print('''Your chances to win the big prize with {:,} tickets are {:.7f}%.
In other words, you have 1 in {:,} chances to win'''.format(n_tickets, percentage, int(combinations_simplified))

In [34]:
# test the function
test_inputs = [1, 10, 100, 10000, 1000000, 6991908, 13983816]
for test in test_inputs:
    multi_ticket_probability(test)

Your chances to win the big prize with one ticket are 0.0000072%.
In other words, you have a 1 in 13,983,816 chance to win.
Your chances to win the big prize with 10 tickets are 0.0000715%.
In other words, you have 1 in 1,398,382 chances to win
Your chances to win the big prize with 100 tickets are 0.0007151%.
In other words, you have 1 in 139,838 chances to win
Your chances to win the big prize with 10,000 tickets are 0.0715112%.
In other words, you have 1 in 1,398 chances to win
Your chances to win the big prize with 1,000,000 tickets are 7.1511238%.
In other words, you have 1 in 14 chances to win
Your chances to win the big prize with 6,991,908 tickets are 50.0000000%.
In other words, you have 1 in 2 chances to win
Your chances to win the big prize with 13,983,816 tickets are 100.0000000%.
In other words, you have 1 in 1 chances to win


## Less Winning Numbers – Function

For extra context, in most 6/49 lotteries there are smaller prizes if a player's ticket match two, three, four, or five of the six numbers drawn. As a consequence, the users might be interested in knowing the probability of having two, three, four, or five winning numbers.

These are the engineering details we'll need to be aware of:

- Inside the app, the user inputs:
 - six different numbers from 1 to 49; and
 - an integer between 2 and 5 that represents the number of winning numbers expected
- Our function prints information about the probability of having the inputted number of winning numbers.


In [37]:
def probability_less_6(n_winning_numbers):
    n_combos = combinations(6,n_winning_numbers)
    n_combos_remaining = combinations(49 - n_winning_numbers, 6 - n_winning_numbers)
    n_successful_outcomes = n_combos * n_combos_remaining
    n_combos_total = combinations(49,6)
    
    probability = n_successful_outcomes / n_combos_total
    percentage = probability * 100
    
    combinations_simplified = round(n_combos_total/n_successful_outcomes)
    
    print('''Your chances of having {} winning numbers is {:6f}%.
In other words, you have 1 in {:,} chances to win.'''.format(n_winning_numbers,
                                                           percentage,
                                                           int(combinations_simplified))

    
    
    

In [39]:
# test
test_numbers = [2,3,4,5]
for test in test_numbers:
    probability_less_6(test)
    # output delimiter
    print('----------------')

Your chances of having 2 winning numbers is 19.132653%.
In other words, you have 1 in 5 chances to win
----------------
Your chances of having 3 winning numbers is 2.171081%.
In other words, you have 1 in 46 chances to win
----------------
Your chances of having 4 winning numbers is 0.106194%.
In other words, you have 1 in 942 chances to win
----------------
Your chances of having 5 winning numbers is 0.001888%.
In other words, you have 1 in 52,969 chances to win
----------------


## Next Steps
Possible features for a second version of the app include:

- Making the outputs even easier to understand by adding fun analogies (for example, we can find probabilities for strange events and compare with the chances of winning in lottery; for instance, we can output something along the lines "You are 100 times more likely to be the victim of a shark attack than winning the lottery").
- Combining the one_ticket_probability() and check_historical_occurrence() to output information on probability and historical occurrence at the same time.